apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metasecure-ai-scripting-beast.fullname" . }}-secret
data:
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | b64enc }}
  BUILD_IMAGE: {{ .Values.env.BUILD_IMAGE | b64enc }}
  REPO_URL_OF_SCRIPT: {{ .Values.env.REPO_URL_OF_SCRIPT | b64enc }}
  PRIVATE_KEY: {{ .Values.env.PRIVATE_KEY | b64enc }}
  NATS_URL: {{ .Values.env.NATS_URL | b64enc }}
  SCRIPT_NAME: {{ .Values.env.SCRIPT_NAME | b64enc }}
     